# Form implementation generated from reading ui file 'generator_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GeneratorDialog(object):
    def setupUi(self, GeneratorDialog):
        GeneratorDialog.setObjectName("GeneratorDialog")
        GeneratorDialog.resize(400, 350)
        self.verticalLayout = QtWidgets.QVBoxLayout(GeneratorDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.password_output = QtWidgets.QLineEdit(parent=GeneratorDialog)
        self.password_output.setReadOnly(True)
        self.password_output.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.password_output.setObjectName("password_output")
        self.verticalLayout.addWidget(self.password_output)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.generate_btn = QtWidgets.QPushButton(parent=GeneratorDialog)
        self.generate_btn.setObjectName("generate_btn")
        self.horizontalLayout.addWidget(self.generate_btn)
        self.copy_btn = QtWidgets.QPushButton(parent=GeneratorDialog)
        self.copy_btn.setObjectName("copy_btn")
        self.horizontalLayout.addWidget(self.copy_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.length_label = QtWidgets.QLabel(parent=GeneratorDialog)
        self.length_label.setObjectName("length_label")
        self.verticalLayout.addWidget(self.length_label)
        self.length_slider = QtWidgets.QSlider(parent=GeneratorDialog)
        self.length_slider.setMinimum(6)
        self.length_slider.setMaximum(32)
        self.length_slider.setProperty("value", 12)
        self.length_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.length_slider.setObjectName("length_slider")
        self.verticalLayout.addWidget(self.length_slider)
        self.uppercase_check = QtWidgets.QCheckBox(parent=GeneratorDialog)
        self.uppercase_check.setChecked(True)
        self.uppercase_check.setObjectName("uppercase_check")
        self.verticalLayout.addWidget(self.uppercase_check)
        self.lowercase_check = QtWidgets.QCheckBox(parent=GeneratorDialog)
        self.lowercase_check.setChecked(True)
        self.lowercase_check.setObjectName("lowercase_check")
        self.verticalLayout.addWidget(self.lowercase_check)
        self.digits_check = QtWidgets.QCheckBox(parent=GeneratorDialog)
        self.digits_check.setChecked(True)
        self.digits_check.setObjectName("digits_check")
        self.verticalLayout.addWidget(self.digits_check)
        self.symbols_check = QtWidgets.QCheckBox(parent=GeneratorDialog)
        self.symbols_check.setChecked(True)
        self.symbols_check.setObjectName("symbols_check")
        self.verticalLayout.addWidget(self.symbols_check)
        self.strength_label = QtWidgets.QLabel(parent=GeneratorDialog)
        self.strength_label.setText("")
        self.strength_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.strength_label.setObjectName("strength_label")
        self.verticalLayout.addWidget(self.strength_label)

        self.retranslateUi(GeneratorDialog)
        QtCore.QMetaObject.connectSlotsByName(GeneratorDialog)

    def retranslateUi(self, GeneratorDialog):
        _translate = QtCore.QCoreApplication.translate
        GeneratorDialog.setWindowTitle(_translate("GeneratorDialog", "Генератор паролей"))
        self.generate_btn.setText(_translate("GeneratorDialog", "Сгенерировать"))
        self.copy_btn.setText(_translate("GeneratorDialog", "Копировать"))
        self.length_label.setText(_translate("GeneratorDialog", "Длина пароля: 12"))
        self.uppercase_check.setText(_translate("GeneratorDialog", "Заглавные буквы (A-Z)"))
        self.lowercase_check.setText(_translate("GeneratorDialog", "Строчные буквы (a-z)"))
        self.digits_check.setText(_translate("GeneratorDialog", "Цифры (0-9)"))
        self.symbols_check.setText(_translate("GeneratorDialog", "Символы (!@#$%)"))
