# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(636, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_layout = QtWidgets.QHBoxLayout()
        self.search_layout.setObjectName("search_layout")
        self.search_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.search_input.setObjectName("search_input")
        self.search_layout.addWidget(self.search_input)
        self.search_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.search_btn.setObjectName("search_btn")
        self.search_layout.addWidget(self.search_btn)
        self.category_filter = QtWidgets.QComboBox(parent=self.centralwidget)
        self.category_filter.setObjectName("category_filter")
        self.category_filter.addItem("")
        self.search_layout.addWidget(self.category_filter)
        self.clear_filters_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clear_filters_btn.setObjectName("clear_filters_btn")
        self.search_layout.addWidget(self.clear_filters_btn)
        self.verticalLayout.addLayout(self.search_layout)
        self.passwords_table = QtWidgets.QTableView(parent=self.centralwidget)
        self.passwords_table.setObjectName("passwords_table")
        self.verticalLayout.addWidget(self.passwords_table)
        self.buttons_layout = QtWidgets.QHBoxLayout()
        self.buttons_layout.setObjectName("buttons_layout")
        self.add_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_btn.setObjectName("add_btn")
        self.buttons_layout.addWidget(self.add_btn)
        self.edit_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.edit_btn.setObjectName("edit_btn")
        self.buttons_layout.addWidget(self.edit_btn)
        self.delete_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.delete_btn.setObjectName("delete_btn")
        self.buttons_layout.addWidget(self.delete_btn)
        self.generate_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.generate_btn.setObjectName("generate_btn")
        self.buttons_layout.addWidget(self.generate_btn)
        self.refresh_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.refresh_btn.setObjectName("refresh_btn")
        self.buttons_layout.addWidget(self.refresh_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttons_layout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.buttons_layout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Password Vault - Хранилище паролей"))
        self.search_input.setPlaceholderText(_translate("MainWindow", "Поиск по сайту, логину или категории..."))
        self.search_btn.setText(_translate("MainWindow", "Поиск"))
        self.category_filter.setItemText(0, _translate("MainWindow", "Все категории"))
        self.clear_filters_btn.setText(_translate("MainWindow", "Сбросить"))
        self.add_btn.setText(_translate("MainWindow", "Добавить пароль"))
        self.edit_btn.setText(_translate("MainWindow", "Редактировать"))
        self.delete_btn.setText(_translate("MainWindow", "Удалить"))
        self.generate_btn.setText(_translate("MainWindow", "Генератор паролей"))
        self.refresh_btn.setText(_translate("MainWindow", "Обновить"))
